Command learnpack audit done
learnpack/learnpack-cli pull request #10
Opened 2021-08-11 02:21 UTC by tommygonzaleza

2021-08-11 19:54 UTC, alesanchezr requested changes

2021-08-11 19:54 UTC, alesanchezr commented on src/commands/audit.js
> +        if (!this.configManager.get().repository) errors.push({exercise: null, msg: "The repository property is not in the configuration object"})
Can I type whatever I want? or it validates that repository is a URL?

2021-08-11 19:54 UTC, alesanchezr commented on src/commands/audit.js
> +        if (!this.configManager.get().slug) errors.push({exercise: null, msg: "The slug property is not in the configuration object"})
better to store the config once in a variable instead of calling the `.get` method every time.

```js
const config = this.configManager.get()
```

2021-08-11 19:54 UTC, alesanchezr commented on src/commands/audit.js
> +        const findInFile = (types, content) => {
This type of functions are better somewhere [inside the utils folder](https://github.com/learnpack/learnpack-cli/tree/learnpack/src/utils) because they are probably going to be reused by learnpack in other commands in the future.

this.configManager.get()

2021-08-11 19:54 UTC, alesanchezr commented on src/commands/audit.js
> +const request = require('request');
We already have the `node-fetch` package for this purpose, why use `request`?

2021-08-11 19:54 UTC, alesanchezr commented on src/commands/audit.js
> +                request(url, function (error, res, body) {
Migrate this type of requests to `node-fetch` instead.

Also important: Requests with METHOD=HEAD instead of GET are way faster because they don't download the body, the only download the HEAD.

2021-08-12 02:24 UTC, tommygonzaleza commented on src/commands/audit.js
> +        if (!this.configManager.get().slug) errors.push({exercise: null, msg: "The slug property is not in the configuration object"})
Fixed.

2021-08-12 02:25 UTC, tommygonzaleza commented on src/commands/audit.js
> +        if (!this.configManager.get().repository) errors.push({exercise: null, msg: "The repository property is not in the configuration object"})
Fixed. Function that checks if it is a url and if it is, it check if it is a valid url added.

2021-08-12 18:30 UTC, tommygonzaleza commented on src/commands/audit.js
> +        const findInFile = (types, content) => {
All reusable functions migrated to utils. Fixed.

2021-08-12 19:50 UTC, tommygonzaleza commented on src/commands/audit.js
> +const request = require('request');
All requests changed to node-fetch. Fixed.

2021-08-12 19:50 UTC, tommygonzaleza commented on src/commands/audit.js
> +                request(url, function (error, res, body) {
All requests are using method HEAD now. Fixed.

2021-08-12 22:50 UTC, alesanchezr approved these changes

2021-08-12 22:50 UTC, merged